set_effect:
  name: Set animation effect
  description: Run an animation effect on a Pixie device.
  target:
    entity:
      integration: pixie
      domain: light
  fields:
    effect:
      name: Effect
      description: Name of the Pixie animation effect.
      example: "Rainbow"
      required: true
      selector:
        select:
          options:
            - "ColorLoop"
            - "Rainbow"
            - "DoubleRainbow"
            - "RainbowChase"
            - "RunningLights"
            - "TwoColors"
            - "ThreeColors"
            - "ColorPeaks"
            - "Sparks"
            - "Comet"
            - "CometWithParticles"
            - "RandomComets"
            - "ColorFadings"
            - "Sparkles"
            - "SparklesOnColor"
            - "SparklesOnColorLoop"
            - "RainbowWipesUp"
            - "RainbowWipesDown"
            - "ColorWipes"
            - "Chain"
            - "BrokenLamp"
            - "FastPixels"
            - "BrightStripes"
            - "DarkStripes"
            - "MulticolorBurst"
            - "OneColorBurst"
            - "RandomColorBurst"
            - "ColorPendulum"
            - "RainbowScan"
            - "DoubleRainbowScan"
            - "RandomColor"
            - "ChaseDown"
            - "ChaseUp"
            - "Chase2Down"
            - "Chase2Up"
            - "SporadicMeteors"
            - "Dots"
            - "RGBScanner"
            - "Twinkles"
            - "PixelQueue"
            - "PeriodicMeteorsUp"
            - "PeriodicMeteorsDown"
            - "Flicker"
            - "MultiplePixelQueues"
            - "MultipleColorPixelQueues"
            - "Fireworks"
            - "Strobe"
            - "BigSparks"
            - "RunAndLightUp"
            - "Moths"
            - "Breathe"
            - "Pixie"
            - "Neutrinos"
            - "Emitter"
            - "BlackHole"
            - "ColorRunsUp"
            - "ColorRunsDown"
            - "LightBars"
            - "Fireworks2"
            - "Paintbrush"
            - "Lightning"
            - "DarkSparklesOnColor"
            - "Noise"
            - "Particles"
            - "Curtains"
            - "Scanner"
    parameter1:
      name: Parameter 1
      description: The parameter1 defines a speed of the effect. It's a number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    parameter2:
      name: Parameter 2
      description: The parameter2 defines an intensity of the effect. It's a number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    brightness:
      name: Brightness
      description: Brightness of the effect. The valid value is between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    rgb_color:
      name: RGB color
      description: A list containing three integers between 0 and 255 representing the RGB (red, green, blue) color for the effect.
      advanced: true
      example: "[255, 100, 50]"
      selector:
        object:

set_random_effect:
  name: Set random animation effect
  description: Run a random animation effect on a Pixie device.
  target:
    entity:
      integration: pixie
      domain: light
  fields:
    parameter1:
      name: Parameter 1
      description: The parameter1 defines a speed of the effect. If the value is not specified a random number is generated between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    parameter2:
      name: Parameter 2
      description: The parameter2 defines an intensity of the effect. If the value is not specified a random number is generated between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    brightness:
      name: Brightness
      description: Brightness of the effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    rgb_color:
      name: RGB color
      description: A list containing three integers between 0 and 255 representing the RGB (red, green, blue) color for the effect. If the color is not specified a random color is generated instead.
      advanced: true
      example: "[255, 100, 50]"
      selector:
        object:

set_picture:
  name: Set static effect
  description: Run a static effect on a Pixie device.
  target:
    entity:
      integration: pixie
      domain: light
  fields:
    picture:
      name: Picture
      description: Name of the Pixie picture effect.
      example: "Rainbow"
      required: true
      selector:
        select:
          options:
            - "Rainbow"
            - "Rainbow2"
            - "Rainbow3"
            - "Rainbow4"
            - "Dots"
            - "Stripes"
            - "ProgressBar"
            - "Noise"
    parameter1:
      name: Parameter 1
      description: The parameter1 of the picture effect. It's a number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    parameter2:
      name: Parameter 2
      description: The parameter2 the picture effect. It's a number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    brightness:
      name: Brightness
      description: Brightness of the effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    rgb_color:
      name: RGB color
      description: A list containing three integers between 0 and 255 representing the RGB (red, green, blue) color for the effect.
      advanced: true
      example: "[255, 100, 50]"
      selector:
        object:

turn_on_transition:
  name: Turn on with transition
  description: Turn on a pixie device with a transition effect.
  target:
    entity:
      integration: pixie
      domain: light
  fields:
    transition_name:
      name: Transition
      description: Name of the Pixie transition effect.
      example: "Fade"
      required: true
      selector:
        select:
          options:
            - "Fade"
            - "Unfold"
            - "Fold"
            - "Unroll"
            - "Roll"
            - "Dots"
            - "FadeOut"
            - "SinIn"
            - "SinOut"
            - "Paintbrush"
            - "Curtains"
    transition:
      name: Transition time
      description: Transition time in seconds Number between 0 and 4096.
      required: true
      selector:
        number:
          min: 0
          max: 4096
    parameter1:
      name: Parameter 1
      description: The parameter1 of the transition effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    parameter2:
      name: Parameter 2
      description: The parameter2 the transition effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    brightness:
      name: Brightness
      description: Brightness of the effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    rgb_color:
      name: RGB color
      description: A list containing three integers between 0 and 255 representing the RGB (red, green, blue) color towards which the transition runs. If the color is not specified the device will be turned off with the specified transition.
      required: true
      example: "[255, 100, 50]"
      selector:
        object:

turn_off_transition:
  name: Turn off with transition
  description: Turn off a pixie device with a transition effect.
  target:
    entity:
      integration: pixie
      domain: light
  fields:
    transition_name:
      name: Transition
      description: Name of the Pixie transition effect.
      example: "Fade"
      required: true
      selector:
        select:
          options:
            - "Fade"
            - "Unfold"
            - "Fold"
            - "Unroll"
            - "Roll"
            - "Dots"
            - "FadeOut"
            - "SinIn"
            - "SinOut"
            - "Paintbrush"
            - "Curtains"
    transition:
      name: Transition time
      description: Transition time in seconds Number between 0 and 4096.
      required: true
      selector:
        number:
          min: 0
          max: 4096
    parameter1:
      name: Parameter 1
      description: The parameter1 of the transition effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
    parameter2:
      name: Parameter 2
      description: The parameter2 the transition effect. Number between 0 and 255.
      selector:
        number:
          min: 0
          max: 255
